import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className="max-w-2xl m-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Staatliches&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Link href={'/dictionary'}>
        <a>
          <div className="shadow-around p-10 rounded-md my-5 cursor-pointer">
            Slovnik
          </div>
        </a>
      </Link>
    </div>
  );
};

export default Home;
