import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
export { getStaticProps } from '../utils/localization';

const Home: NextPage = () => {
  return (
    <div className="max-w-3xl m-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={'/dictionary'}>
        <a>
          <div className="shadow-around p-10 rounded-md my-5 cursor-pointer">Slovnik</div>
        </a>
      </Link>
    </div>
  );
};

export default Home;
