name: Movapp run all tests

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Lint
        run: yarn lint

      - name: Unit test
        run: yarn lint

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"